
-- physics:

STATIC_TERRAIN		= 1
STATIC_FLOORS       = STATIC_TERRAIN * 2
STATIC_WALLS        = STATIC_FLOORS * 2
BULLET_WALLS		= STATIC_WALLS * 2
DYNAMIC_PROPS		= BULLET_WALLS * 2
DYNAMIC_CHARACTER	= DYNAMIC_PROPS * 2
SENSOR				= DYNAMIC_CHARACTER * 2
PORTAL_A      		= SENSOR * 2
PORTAL_B      		= PORTAL_A * 2


-- visibility:
NON_PLAYER	= 1
PLAYER		= NON_PLAYER * 2
